### ISSUE TITLE
Remove cuDNN dep?

### ISSUE THREAD

**Issue by liuyxpp** [LuxDL/LuxCUDA.jl#20]
Currently, the registered cuDNN seems frozen at v1.3.2, but the latest cuDNN inside CUDA.jl repo is v1.4.0. If LuxCUDA is installed, then CUDA will be restricted to v5.4.3 and Lux v1.0.5:

```julia
pkg> add LuxCUDA, CUDA, Lux
pkg> st
⌅ [052768ef] CUDA v5.4.3
⌃ [b2108857] Lux v0.5.47
  [d0bbae9a] LuxCUDA v0.3.3
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`
```

Then using `update`:

```julia
pkg> up
pkg> st
⌅ [052768ef] CUDA v5.4.3
⌃ [b2108857] Lux v1.0.5
  [d0bbae9a] LuxCUDA v0.3.3
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`
```

**Comment by avik-pal** [comment]
Bundling CUDA and cuDNN together is the whole point of this package :sweat:

**Comment by liuyxpp** [comment]
> Bundling CUDA and cuDNN together is the whole point of this package 😓

But this does not answer my question: how to upgrade CUDA and Lux to their latest version using LuxCUDA?

**Comment by avik-pal** [comment]
cuDNN was released a few hrs back. Though I will say if you are using Lux in unison with the SciML packages, you won't be able to install the newest versions since SciML isn;t updated for the latest enzymecore release
